[env:n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino

monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1

upload_flags =
    --before
    usb_reset
    --connect-attempts
    10
